name: Production - Build & Release
 
on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - uses: azure/docker-login@v1
        with:
          login-server: vpacrlibrary.azurecr.io
          username: VPACRLibrary
          password: 4WiQlmP/nWipkosQPstMcoUwQd3u0fAcZCrYbsFAL1+ACRA92WVT
 
      - run: |
          docker build . -t vpacrlibrary.azurecr.io/library:production
          docker push vpacrlibrary.azurecr.io/library:production
