# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - TempCheckACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tempcheck.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2be00ee7a1dc4f0fa7a67a925391e4cd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_24b833e2ed1e4046b750f50cc575ff39 }}
        
    - name: Get short SHA
      id: short_sha
      run: echo "::set-output name=short_sha::$(echo ${{ github.sha }} | cut -c1-8)"
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: tempcheck.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2be00ee7a1dc4f0fa7a67a925391e4cd }}/librarywebimagecheck:${{ steps.short_sha.outputs.short_sha }}
        file: ./Dockerfile
   

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'TempCheckACR'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c7acdf581df43d7ae83b57dd2f41bd3 }}
        images: 'tempcheck.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2be00ee7a1dc4f0fa7a67a925391e4cd }}/librarywebimagecheck:production'
