name: Production - Build & Release
 
on:
  push:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - uses: azure/docker-login@v1
        with:
          login-server: libraryvp.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_NAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
      - run: |
          docker build . -t libraryvp.azurecr.io/libraryweb:production
          docker push libraryvp.azurecr.io/libraryweb:production
